# Generated by Django 3.2.3 on 2021-06-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='timestamp',
        ),
    ]
