# Generated by Django 3.2.3 on 2021-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0002_remove_logs_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='path',
            field=models.CharField(max_length=255, verbose_name='path'),
        ),
    ]
