# Generated by Django 3.2.3 on 2021-06-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0003_alter_logs_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['path', 'method']},
        ),
    ]
