# Generated by Django 3.2.3 on 2021-06-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0004_alter_logs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['path']},
        ),
    ]
