# Generated by Django 3.2.3 on 2021-06-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0006_auto_20210615_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('method', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
