# Generated by Django 3.2.3 on 2021-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0008_alter_logs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['path', 'method'], 'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='method',
            field=models.CharField(max_length=255, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Path'),
        ),
    ]
