# Generated by Django 3.2.3 on 2021-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0009_auto_20210615_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='method',
            field=models.CharField(max_length=255, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='path',
            field=models.CharField(max_length=255, verbose_name='path'),
        ),
    ]
