# Generated by Django 3.2.3 on 2021-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogs', '0010_auto_20210615_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=None, verbose_name='timestamp'),
        ),
    ]
