# Generated by Django 3.2.3 on 2021-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2, verbose_name='Число юзеров')),
            ],
            options={
                'verbose_name': 'Создание юзеров',
            },
        ),
    ]
